### ISSUE TITLE
Make excread more robust

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/glodap#14]
Ref https://github.com/jonasfh/xover/issues/86

Trying to read file 06MT20091126.csv fails: 

> Could not read file /vagrant/d2qc/user_data/UID_1/0__06MT20091126.csv
Traceback (most recent call last):
  File "/vagrant/lib/glodap/util/excread.py", line 35, in excread
    return _excread(excfile)
  File "/vagrant/lib/glodap/util/excread.py", line 89, in _excread
    signature = matches.group(4)
AttributeError: 'NoneType' object has no attribute 'group'

This is caused by the file starting with `BOTTLE 20091126FB.... ` instead of `BOTTLE,20091126FB`. Allowing both variants should not pose a problem. 

There are also other issues in this file, investigating further

**Comment by jonasfh** [comment]
[06MT20091126.txt](https://github.com/BjerknesClimateDataCentre/glodap/files/3492349/06MT20091126.txt)

**Comment by jonasfh** [comment]
This issue was fixed directly in master
